export default {
  marks: {
    FLAG: 'FLAG',
    QUESTION: 'QUESTION',
    NONE: 'NONE'
  },
  timer: {
    SET_TIMER_SECONDS: 'SET_TIMER_SECONDS',
    SET_TIMER_ACTION: 'SET_TIMER_ACTION'
  },
  game: {
    UPDATE_ROWS_AND_COLS_QTY: "UPDATE_ROWS_AND_COLS_QTY",
    UPDATE_CELLS_GRID: "UPDATE_CELLS_GRID"
  },
  configForm: {
    TOGGLE_CONFIG_FORM: "TOGGLE_CONFIG_FORM",
    TOGGLE_USE_CELL_QUESTION_MARK: "TOGGLE_USE_CELL_QUESTION_MARK"
  },
  toggle: {
    UPDATE_QUESTION_MARK_ACCESS: "UPDATE_QUESTION_MARK_ACCESS"
  }
};